transaction.webhook.starling:
    path: /webhook/starling/transaction
    controller: App\Controller\Webhook\StarlingController
    methods: [POST]

oauth.redirect:
    path: /auth
    controller: App\Controller\AuthController
index:
    path: /
    controller: App\Controller\HomeController

transaction.list:
    path: /transactions
    controller: App\Controller\TransactionListController
