transaction.webhook.starling:
    path: /webhook/starling/transaction
    controller: App\Controller\Webhook\StarlingController
    methods: [POST]

oauth.redirect:
    path: /auth
    controller: App\Controller\AuthController
index:
    path: /
    controller: App\Controller\HomeController

transaction.list:
    path: /transactions
    controller: App\Controller\TransactionListController

register:
    path: /register
    controller: App\Controller\RegisterController

complete:
    path: /complete
    controller: App\Controller\CompleteController

overview:
    path: /overview
    controller: App\Controller\OverviewController

distribute:
    path: /distribute
    controller: App\Controller\DistributeController
